language:
  - cpp
matrix:
  include:
    - os: linux
      env: STD=c++11 MAIN_BUILD=true
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'cmake', 'valgrind']
    - os: linux
      env: STD=c++17
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'cmake']
    #- os: linux
    #  env: CXX=clang++
dist: trusty
sudo: required
before_install:
  - pyenv install 3.6.0
  - pyenv global 3.6.0
  - pip3 install gcovr
script:
  - export CSV_TEST_ROOT=$PWD/tests
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-8
  - make csv_coverage;
after_success:
  - if [ "$MAIN_BUILD" == "true" ]; then
        doxygen Doxyfile;
    fi;
deploy:
  - provider: pages
  - skip_cleanup: true
  - github_token: $GITHUB_TOKEN
  - keep_history: true
  - local_dir: docs
  - target_branch: gh-pages
  - on:
    - branch: master
    - branch: cmake_apr_26_2020