language:
  - cpp
matrix:
  include:
    - os: linux
      env: STD=c++11 MAIN_BUILD=true
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'cmake', 'valgrind', 'lcov']
    - os: linux
      env: STD=c++17
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'cmake', 'lcov']
    #- os: linux
    #  env: CXX=clang++
dist: trusty
# before_install:
#  - pyenv install 3.6.0
#  - pyenv global 3.6.0
#  - pip3 install gcovr
script: 
  - export CSV_TEST_ROOT=$PWD/tests
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-8
  - make csv_test;
  - ./tests/csv_test;
  - sh ./get_code_cov.sh;
after_success:
  - if [ "$MAIN_BUILD" == "true" ]; then
        bash <(curl -s https://codecov.io/bash);
    fi;
