matrix:
  include:
    - os: linux
      env: STD=c++11 MAIN_BUILD=true
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'valgrind']
    - os: linux
      env: STD=c++17
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
    #- os: linux
    #  env: CXX=clang++
dist: trusty
sudo: required
language:
  - cpp
script:
  - make run_csv_test
  - if [ "$MAIN_BUILD" == "true" ]; then
        cmake -DCMAKE_BUILD_TYPE=DEBUG -G "Unix Makefiles";
        make csv_coverage;
    fi;
after_success:
  - if [ "$MAIN_BUILD" == "true" ]; then
        bash <(curl -s https://codecov.io/bash);
    fi;
