matrix:
  include:
    - os: linux
      env: STD=c++11 MAIN_BUILD=true
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'lcov', 'valgrind']
    - os: linux
      env: STD=c++17
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'lcov']
    #- os: linux
    #  env: CXX=clang++
dist: trusty
sudo: required
language:
  - cpp
script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz"
        mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi;
  - if [ "$MAIN_BUILD" == "true" ]; then
        CXX=g++-8 cmake -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles";
        make csv_coverage;
    fi;
after_success:
  - if [ "$MAIN_BUILD" == "true" ]; then
        bash <(curl -s https://codecov.io/bash);
    fi;
