language:
  - cpp
matrix:
  include:
    - os: linux
      env: STD=c++11 MAIN_BUILD=true
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'cmake', 'valgrind', 'lcov']
    - os: linux
      env: STD=c++17
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'cmake', 'lcov']
    #- os: linux
    #  env: CXX=clang++
dist: trusty
# before_install:
#  - pyenv install 3.6.0
#  - pyenv global 3.6.0
#  - pip3 install gcovr
script: 
  - sudo apt-get install --only-upgrade lcov
  - lcov --version
  - export CSV_TEST_ROOT=$PWD/tests
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON
  - make csv_coverage;
  #- if [ "$MAIN_BUILD" == "true" ]; then
        #make csv_coverage;
  #  fi;
after_success:
  - if [ "$MAIN_BUILD" == "true" ]; then
        cd include/internal/CMakeFiles/csv.dir
        bash <(curl -s https://codecov.io/bash);
    fi;
