matrix:
  include:
    - os: linux
      env: STD=c++11 MAIN_BUILD=true
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'cmake', 'valgrind']
    - os: linux
      env: STD=c++17
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'cmake']
    #- os: linux
    #  env: CXX=clang++
dist: trusty
sudo: required
language:
  - cpp
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug
  - make csv_test
  - ./tests/csv_test
  - if [ "$MAIN_BUILD" == "true" ]; then
        make csv_coverage;
        #make valgrind;
    fi;
#after_success:
#  - if [ "$MAIN_BUILD" == "true" ]; then
#        cd test_results;
#        bash <(curl -s https://codecov.io/bash);
#    fi;
